### PR TITLE
Initial Testing UI

### PR DESCRIPTION
**Pull request by AlexWHughes**
It can start the recording but my knowledge isn't good enough to get some of the functionality like duration to work

### CODE REVIEW

**Comment by AlexWHughes** [comment]
This resolves my duration issue so the only thing left is working out how to get page refreshing to work properly. ChatGPT seems to be quite confused on this one. @dkulp

**Comment by dkulp** [comment]
Best option for page refresh is from the browser side.   Ideally, it wouldn't even do a full refresh.  You'd start a timer and periodically do a GET on something that would return a small "status" json and then use javascript to update the values on the currently displayed page.

**Comment by AlexWHughes** [comment]
Thanks, I didn't expect such a prompt reply. I'll have a look. Don't merge this till you're happy or I at least get all the features in I want (You don't have to merge it at all I just figured someone else might find it useful)

**Comment by AlexWHughes** [comment]
Alright I've tried that.  I get the following error as obviously its loading the full page rather than just the JSON file. 
XMLHttpRequest.<anonymous> (jquery-latest.min.js?ref=1724497119:2:80265)
error @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:434
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
l @ jquery-latest.min.js?ref=1724497119:2
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
load
send @ jquery-latest.min.js?ref=1724497119:2
ajax @ jquery-latest.min.js?ref=1724497119:2
updateStatus @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:421
(anonymous) @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:440
e @ jquery-latest.min.js?ref=1724497119:2
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
setTimeout
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
fire @ jquery-latest.min.js?ref=1724497119:2
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
ready @ jquery-latest.min.js?ref=1724497119:2
P @ jquery-latest.min.js?ref=1724497119:2Understand this error
29plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:434 AJAX Error: parsererror SyntaxError: Unexpected token '<', "    <!-- Falco"... is not valid JSON
    at parse (<anonymous>)
    at jquery-latest.min.js?ref=1724497119:2:77349
    at l (jquery-latest.min.js?ref=1724497119:2:77466)
    at XMLHttpRequest.<anonymous> (jquery-latest.min.js?ref=1724497119:2:80265)
error @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:434
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
l @ jquery-latest.min.js?ref=1724497119:2
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
load
send @ jquery-latest.min.js?ref=1724497119:2
ajax @ jquery-latest.min.js?ref=1724497119:2
updateStatus @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:421
setInterval
(anonymous) @ plugin.php?_menu=content&plugin=fpp-Capture&page=plugin_setup.php:441
e @ jquery-latest.min.js?ref=1724497119:2
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
setTimeout
(anonymous) @ jquery-latest.min.js?ref=1724497119:2
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
fire @ jquery-latest.min.js?ref=1724497119:2
c @ jquery-latest.min.js?ref=1724497119:2
fireWith @ jquery-latest.min.js?ref=1724497119:2
ready @ jquery-latest.min.js?ref=1724497119:2
P @ jquery-latest.min.js?ref=1724497119:2

Is there any quick way around this @dkulp as obviously there is no "direct link" I can supply to the php file

Screenshot 2024-08-25 at 1 35 42 AM

**Pull request closed without merging**
